In [12]:
import numpy as np
import pandas as pd
df1 = pd.Series({'a' : 1})

print (df1)

df1.values

print (df1.index)

a    1
dtype: int64
Index(['a'], dtype='str')

In [16]:
df1 = pd.DataFrame({'name':['ali','abass','Hamza','hurain'], 'age' : [20,30,35,np.nan]})
print(df1)

     name   age
0     ali  20.0
1   abass  30.0
2   Hamza  35.0
3  hurain   NaN

In [24]:
df1.head(0)

Empty DataFrame
Columns: [name, age]
Index: []

In [27]:
df1.tail(2)

     name   age
2   Hamza  35.0
3  hurain   NaN

In [ ]:
# Using a larger dataset
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Age': [25, 30, 35, 28, 25, 32],
    'Salary': [50000, 60000, 70000, 55000, 52000, 68000],
    'Department': ['HR', '', 'IT', 'Finance', 'HR', 'IT'],
    'Experience': [2, 5, 8, 3, 2, 6]
})

# head() and tail()
print(df.head(2))
print(df.tail(2))

# unique() and nunique()
print(df['Department'].unique())
print(df['Department'].nunique())

# value_counts()
print(df['Department'].value_counts())
print(df['Age'].value_counts())

    Name  Age  Salary Department  Experience
0  Alice   25   50000         HR           2
1    Bob   30   60000        NaN           5
    Name  Age  Salary Department  Experience
4    Eve   25   52000         HR           2
5  Frank   32   68000         IT           6
<StringArray>
['HR', nan, 'IT', 'Finance']
Length: 4, dtype: str
3
Department
HR         2
IT         2
Finance    1
Name: count, dtype: int64
Age
25    2
30    1
35    1
28    1
32    1
Name: count, dtype: int64

In [33]:
df['Department'].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [64]:
df.iloc[:,1].replace('IT', np.nan)

0    25
1    30
2    35
3    28
4    25
5    32
Name: Age, dtype: int64

In [50]:
df.isnull().sum()

Name          0
Age           0
Salary        0
Department    0
Experience    0
dtype: int64

In [62]:
df.dropna()

      Name  Age  Salary Department  Experience
0    Alice   25   50000         HR           2
2  Charlie   35   70000         IT           8
3    David   28   55000    Finance           3
4      Eve   25   52000         HR           2
5    Frank   32   68000         IT           6

In [69]:
filtered_employees = df[(df['Department'] == 'IT') & (df['Age'] > 30)]
print(filtered_employees)

      Name  Age  Salary Department  Experience
2  Charlie   35   70000         IT           8
5    Frank   32   68000         IT           6