In [93]:
import pandas as pd
import numpy as np

Data Reading Tasks:

In [94]:
#1.Read the dataset from a CSV file into a pandas DataFrame
sales_df=pd.read_csv('sales.csv')
sales_df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [95]:
#2.Display the first 8 rows and check the basic structure of the dataset using .info()
sales_df.head(8)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [96]:
#3.Get statistical summary of numerical columns using .describe()
sales_df.describe(include='all')

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
count,500.000000,500,500,500,500,500,500.000000,500.000000,500.00000,500.000000
unique,NaN,267,4,6,2,2,NaN,NaN,NaN,NaN
top,NaN,2024-04-08,North,Mouse,Electronics,Returning,NaN,NaN,NaN,NaN
freq,NaN,6,151,96,266,261,NaN,NaN,NaN,NaN
mean,250.500000,NaN,NaN,NaN,NaN,NaN,4.968000,768.158000,0.14666,3333.059560
std,144.481833,NaN,NaN,NaN,NaN,NaN,2.569081,404.010497,0.08612,2693.185995
min,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,50.000000,0.00000,67.320000
25%,125.750000,NaN,NaN,NaN,NaN,NaN,3.000000,432.750000,0.08000,1120.867500
50%,250.500000,NaN,NaN,NaN,NaN,NaN,5.000000,742.000000,0.15000,2582.805000
75%,375.250000,NaN,NaN,NaN,NaN,NaN,7.000000,1094.500000,0.22000,4998.030000
max,500.000000,NaN,NaN,NaN,NaN,NaN,9.000000,1499.000000,0.30000,12700.800000

In [97]:
#4.Check column names and rename any columns for better readability (e.g., rename 'order_id' to 'OrderID')
sales_df.rename(columns={'price': 'Amount'}, inplace=True)
sales_df

,order_id,date,region,product,category,customer_type,quantity,Amount,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

Data Cleaning Tasks:

In [98]:
#5.Check for missing values in each column and handle them appropriately
print(sales_df.isnull().sum())

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
Amount           0
discount         0
sales            0
dtype: int64

In [99]:
#6.Check for duplicate rows and remove any duplicates if found
sales_count = sales_df.duplicated().sum()
sales_df.drop_duplicates(inplace=True)
print(sales_df.shape)

(500, 10)

In [100]:
#7.Convert 'date' column to datetime format
sales_df.rename(columns={'date': 'Datetime'}, inplace=True)
sales_df

,order_id,Datetime,region,product,category,customer_type,quantity,Amount,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [101]:
#8.Check data types of all columns and convert if necessary (e.g., ensure 'quantity' is int, 'price' is float)
print(sales_df.dtypes)

order_id           int64
Datetime             str
region               str
product              str
category             str
customer_type        str
quantity           int64
Amount             int64
discount         float64
sales            float64
dtype: object

In [102]:
#9.Standardize 'region' values (ensure consistent capitalization and remove extra spaces)
sales_df['region'] = sales_df['region'].str.title()
sales_df

,order_id,Datetime,region,product,category,customer_type,quantity,Amount,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [103]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   Datetime       500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   Amount         500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB

In [104]:
#11.Calculate total sales by region and find which region has the highest sales

total_sales = sales_df.groupby("region")["sales"].sum().idxmax()
total_sales

'North'

In [105]:
#12.Find the average discount given for each product category

In [106]:
#13.Analyze customer ratings - calculate average rating by customer type (New vs Returning)ratings = sales_df.groupby('customer_type')('sales').agg("mean")

In [107]:
#13.Find top 5 products by quantity sold
top_5_products = sales_df.groupby('Product')['Quantity'].sum().agg('largest(5)')

KeyError: 'Product'